Deleted .gitignore
acmatnau/practiceGitRepo pull request #2
Opened 2019-10-11 01:39 UTC by mpeiffer

I just deleted everything.

2019-10-11 04:23 UTC, ChrisKeefe requested changes
@mpeiffer, your PR made me laugh really hard! I could probably use more sleeeeep.... Do you want some extra credit? Can you push another commit up to the same branch that reverts all of these changes? 

@ mention me in a reply to this pull request either way. I'd be happy to merge or close this sucker if you don't want to deal with extra credit.... Incidentally, do you know what a .gitignore does? Super useful lil files...

2019-10-11 16:02 UTC, mpeiffer commented
@ChrisKeefe I can revert the changes later today. :) Also, I don't know what a .gitignore does but it seems like something worth looking into.

2019-10-14 18:38 UTC, ChrisKeefe approved these changes

2019-10-14 18:39 UTC, ChrisKeefe commented
Nice! You tackled this exactly the way I had hoped. Merging!

2019-10-14 18:39 UTC, merged